### ISSUE TITLE
Add strongold for Mac security?

### ISSUE THREAD

**Issue by alichtman** [cquick97/security-scripts#2]
https://github.com/alichtman/stronghold

**Comment by cquick97** [comment]
Thanks. This repo was pretty much specifically for the CyberPatriot competition, where the scripts helped fix the vulnerabilities in the virtual machines they provided. I haven't looked at these in a while, thanks for the blast from the past haha

Stronghold looks quite interesting though. I'll check it out for my personal MacOS stuff.

Thanks for sharing! 👍
